### ISSUE TITLE
Replace busparse package

### ISSUE THREAD

**Issue by fgypas** [zavolanlab/merge_kallisto#6]
The package busparse is unstable and it is not easy to install together with the other packages. From the package, we use the function tr2g_gtf 
https://github.com/zavolanlab/merge_kallisto/blob/master/R/merge_kallisto.R#L142 that creates a transcript id gene id dataframe based on a gtf file. This should be replaced with something else.

**Comment by paulaidt** [comment]
Removed busparse package. Using rtracklayer package to read the annotation file in the Rscript and create a transcript id gene id dataframe.

**Comment by fgypas** [comment]
Ok great just push it in a branch and make a pull request.

**Comment by fgypas** [comment]
Fixed in #9
