### ISSUE TITLE
Recude Dockerfile image

### ISSUE THREAD

**Issue by fgypas** [zavolanlab/merge_kallisto#8]
At the moment the docker image generated is more than 2GB. We need to reduce the size of it.

**Comment by fgypas** [comment]
@paulaidt Can you please tell me the versions that you use of the different packages. Also which R version do you use?

**Comment by paulaidt** [comment]
r-base: 3.6.1
bioconductor-rtracklayer:  1.46.0
bioconductor-rhdf5:  2.30.0
r-optparse: 1.6.2

**Comment by fgypas** [comment]
And for tximport?

**Comment by paulaidt** [comment]
Sorry, missed that.
bioconductor-tximport:  1.14.0
